# Problem Set 2
Ayse Mehmeti   

Standard Library Chapter

Problem 1

In [19]:
def list_stats(L):
    return (min(L), max(L), sum(L)/len(L))   
numbers1 = [2, 5, 8]
numbers2 = [10, 20, 30, 40]
numbers3 = [3, 6, 9]

stats1 = list_stats(numbers1)
stats2 = list_stats(numbers2)
stats3 = list_stats(numbers3)

print(list_stats(numbers1)) 
print(list_stats(numbers2))  
print(list_stats(numbers3))   


(2, 8, 5.0)
(10, 40, 25.0)
(3, 9, 6.0)


Problem 2

In [20]:
# int (immutable)
x = 10
y = x
y += 1
print("int:", x, y, x == y)

int: 10 11 False


In [21]:
# str (immutable)
s1 = "hello"
s2 = s1
s2 += " world"
print("str:", s1, s2, s1 == s2)

str: hello hello world False


In [22]:
# list (mutable)
l1 = [1, 2, 3]
l2 = l1
l2.append(4)
print("list:", l1, l2, l1 == l2)

list: [1, 2, 3, 4] [1, 2, 3, 4] True


In [23]:
# tuple (immutable)
t1 = (1, 2, 3)
t2 = t1
t2 += (4,)
print("tuple:", t1, t2, t1 == t2)

tuple: (1, 2, 3) (1, 2, 3, 4) False


In [24]:
# set (mutable)
set1 = {1, 2, 3}
set2 = set1
set2.add(4)
print("set:", set1, set2, set1 == set2)

set: {1, 2, 3, 4} {1, 2, 3, 4} True


Problem 3

In [25]:
import calculator

def hypotenuse(a, b):
    return calculator.sqrt(
        calculator.add(
            calculator.multiply(a, a),
            calculator.multiply(b, b)
        )
    )

print(hypotenuse(3, 4))   # 5.0
print(hypotenuse(5, 12))  # 13.0


5.0
13.0


 Introduction to Numpy chapter

 Problem 1

In [1]:
import numpy as np

def matrix_product():
    # Define matrices A and B
    A = np.array([[3, -1, 4],
                  [1,  5, -9]])

    B = np.array([[ 2,  6, -5,  3],
                  [ 5, -8,  9,  7],
                  [ 9, -3, -2, -3]])

    # Multiply A and B
    product = A @ B   # or np.dot(A, B)
    return product

# Test
print(matrix_product())


[[ 37  14 -32 -10]
 [-54  -7  58  65]]


Problem 2

In [6]:
import numpy as np

def problem2():
    A = np.array([[ 3, 1, 4],
                  [ 1, 5, 9],
                  [-5, 3, 1]])

    A2 = A @ A
    A3 = A @ A @ A

    print("A:\n", A)
    print("A squared:\n", A2)
    print("A cubed:\n", A3)
    print("-A3:\n", -A3)
    print("9*A2:\n", 9*A2)
    print("-15*A:\n", -15*A)

    result = -A3 + 9*A2 - 15*A
    return result

print("Final result:\n", problem2())


A:
 [[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]
A squared:
 [[-10  20  25]
 [-37  53  58]
 [-17  13   8]]
A cubed:
 [[-135  165  165]
 [-348  402  387]
 [ -78   72   57]]
-A3:
 [[ 135 -165 -165]
 [ 348 -402 -387]
 [  78  -72  -57]]
9*A2:
 [[ -90  180  225]
 [-333  477  522]
 [-153  117   72]]
-15*A:
 [[ -45  -15  -60]
 [ -15  -75 -135]
 [  75  -45  -15]]
Final result:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


Problem 5

In [8]:
def problem5():
    A = np.array([[0, 2, 4],
                  [1, 3, 5]])

    B = np.array([[3, 0, 0],
                  [3, 3, 0],
                  [3, 3, 3]])

    C = np.array([[-2, 0, 0],
                  [ 0,-2, 0],
                  [ 0, 0,-2]])

    I = np.eye(3)

    # Now use the correct zero block sizes
    row1 = np.hstack([np.zeros((3,3)), A.T, I])             # [0, A^T, I]
    row2 = np.hstack([A, np.zeros((2,2)), np.zeros((2,3))]) # [A, 0, 0]
    row3 = np.hstack([B, np.zeros((3,2)), C])               # [B, 0, C]

    return np.vstack([row1, row2, row3])

print(problem5())


[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


Object Oriented Programming

Problem 1

In [9]:
class Backpack:
    """
    A Backpack object class.
    
    Attributes:
        name (str): Owner of the backpack.
        color (str): Color of the backpack.
        max_size (int): Maximum capacity of the backpack (default = 5).
        contents (list): Items currently inside the backpack.
    """

    def __init__(self, name, color, max_size=5):
        """
        Initialize a new Backpack object.
        
        Parameters:
            name (str): The owner of the backpack.
            color (str): The color of the backpack.
            max_size (int, optional): Maximum number of items allowed (default = 5).
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):
        """
        Add an item to the backpack if there is space.
        
        Parameters:
            item (str): The item to add.
        """
        if len(self.contents) < self.max_size:
            self.contents.append(item)
        else:
            print("No Room!")

    def dump(self):
        """
        Empty the backpack.
        """
        self.contents = []


# ----------------------------
# Test function
# ----------------------------
def test_backpack():
    testpack = Backpack("Barry", "black")  # make a backpack
    
    # Check attributes
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly")
    
    # Add items
    for item in ["pencil", "pen", "paper", "computer", "snack", "water"]:
        testpack.put(item)
    print("Contents after put():", testpack.contents)
    
    # Dump items
    testpack.dump()
    print("Contents after dump():", testpack.contents)


# Run the test
test_backpack()

No Room!
Contents after put(): ['pencil', 'pen', 'paper', 'computer', 'snack']
Contents after dump(): []


Problem 2

In [10]:
class Jetpack(Backpack):
    """
    A Jetpack object class. Inherits from Backpack.
    
    Attributes:
        name (str): Owner of the jetpack
        color (str): Color of the jetpack
        max_size (int): Maximum number of items it can hold (default = 2)
        contents (list): List of items inside
        fuel (int): Amount of fuel in the jetpack (default = 10)
    """

    def __init__(self, name, color, max_size=2, fuel=10):
        """
        Constructor for Jetpack object.
        
        Parameters:
            name (str): Owner's name
            color (str): Jetpack color
            max_size (int, optional): Maximum number of items (default = 2)
            fuel (int, optional): Amount of fuel (default = 10)
        """
        # Call Backpack constructor to handle name, color, and max_size
        super().__init__(name, color, max_size)
        self.fuel = fuel   # new attribute

    def fly(self, fuel_burn):
        """
        Burn fuel to fly. 
        
        Parameters:
            fuel_burn (int): Amount of fuel to burn
        """
        if fuel_burn <= self.fuel:
            self.fuel -= fuel_burn
        else:
            print("Not enough fuel!")

    def dump(self):
        """
        Empty both contents and fuel.
        """
        self.contents = []
        self.fuel = 0


In [11]:
def test_jetpack():
    jp = Jetpack("Barry", "silver")

    print("Owner:", jp.name)
    print("Color:", jp.color)
    print("Max Size:", jp.max_size)
    print("Fuel:", jp.fuel)
    print("Contents:", jp.contents)

    # Add items
    jp.put("wrench")
    jp.put("helmet")
    jp.put("extra")   # should print "No Room!"
    print("Contents after put():", jp.contents)

    # Fly test
    jp.fly(5)
    print("Fuel after flying:", jp.fuel)

    jp.fly(20)  # should print "Not enough fuel!"
    print("Fuel now:", jp.fuel)

    # Dump test
    jp.dump()
    print("Contents after dump:", jp.contents)
    print("Fuel after dump:", jp.fuel)

# Run the test
test_jetpack()


Owner: Barry
Color: silver
Max Size: 2
Fuel: 10
Contents: []
No Room!
Contents after put(): ['wrench', 'helmet']
Fuel after flying: 5
Not enough fuel!
Fuel now: 5
Contents after dump: []
Fuel after dump: 0
